// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // 核心知识库侧边栏配置
  // 采用 "自动生成" 模式 (Autogenerated)
  // 优势：你只需要在 docs/ 目录下创建文件夹或文件，侧边栏会自动同步更新。
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // '.' 表示从 docs 根目录开始扫描
    },
  ],
};

export default sidebars;
